trigger:
- main
variables:
 location: 'eastus2'
 registryName: 'sarajun'
 acrhostName: 'sarajun.azurecr.io'


stages:
- stage: Build
  displayName: 'Build and Push Docker Image'
  jobs:
  - job: Build
    displayName: 'Build Docker Image'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureResourceGroupDeployment@2
      displayName: 'create a ACR'
      inputs:
        azureSubscription: 'azureSrvcConn'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'cicdpipeline'
        location: '$(location)'
        templateLocation: 'Linked artifact'
        csmFile: '$(System.DefaultWorkingDirectory)/**/azure-container-registry.json'
        overrideParameters: '-registryName "$(registryName)" -sku Standard  -location $(location)'
        deploymentMode: 'Incremental'
    - task: Docker@1
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscriptionEndpoint: 'azureSrvcConn'
        azureContainerRegistry: '$(acrhostName)'
        command: 'Build an image'
        dockerFile: '**/Dockerfile'
        imageName: '$(Build.Repository.Name):$(Build.BuildId)'
      displayName: 'build'
    - task: Docker@1
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscriptionEndpoint: 'azureSrvcConn'
        azureContainerRegistry: '($acrhostname)'
        command: 'Push an image'
        imageName: '$(Build.Repository.Name):$(Build.BuildId)'
      displayName: 'Push the image'