trigger:
- main
variables:
 location: 'eastus2'
 acrHostName: 'sarajuun.azurecr.io'
 registryName: 'sarajun'


stages:
- stage: Build
  displayName: 'Build and Push Docker Image'
  jobs:
  - job: Build
    displayName: 'Build Docker Image'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureResourceGroupDeployment@1
      inputs:
        ConnectedServiceName: 'azure-connection'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'newdeployment'
        
        csmFile: '$(System.DefaultWorkingDirectory)/**/azure-container-registry.json'
        deploymentMode: 'Incremental'
        overrideParameters: '-registryName "$(registryName)" -sku Standard  -location $(location)'
    - task: Docker@1
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscriptionEndpoint: 'azure-connection'
        azureContainerRegistry: '$(acrHostName)'
        command: 'Build an image'
        dockerFile: '**/Dockerfile'
        imageName: '$(Build.Repository.Name):$(Build.BuildId)'
      displayName: 'build'
    - task: Docker@1
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscriptionEndpoint: 'azure-connection'
        azureContainerRegistry: '($acrHostname)'
        command: 'Push an image'
        dockerFile: '**/Dockerfile'
        imageName: '$(Build.Repository.Name):$(Build.BuildId)'
      displayName: 'Push the image'