# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  location: 'eastus'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
        
    - task: PublishPipelineArtifact@1
      inputs:
          targetPath: '$(Pipeline.Workspace)'
          publishLocation: 'pipeline'
          
- stage:
  displayName: Deploy
  jobs:
  - job: Deploy
    steps:
    - task: AzureResourceGroupDeployment@2
      inputs:
        azureSubscription: 'azure-connection'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'Newdeployment'
        location: 'East US'
        templateLocation: 'Linked artifact'
        csmFile: '$(Pipeline.Workspace)/**/ACR.json'
        overrideParameters: '-location "$(location)"'
        deploymentMode: 'Incremental'

        
    
